# ~/.foundry/foundry.toml

# Declare your named endpoints (optional; for forge test / forking)
[rpc_endpoints]
cosmos = "https://devnet-1-evmrpc.ib.skip.build"

# Configure the default profile for cast/forge/anvil
[profile.default]
# Tell Foundry which chain you're targeting:
chain_id     = 306091
# Directly tell cast to use your endpoint:
eth_rpc_url  = "https://devnet-1-evmrpc.ib.skip.build"
# Set EVM version for Solidity compilation
evm_version  = "istanbul"